dataset_name: 'solar'
adj_threshold: 0.1

window: 24
p_block: 0.025
p_point: 0.025
min_seq: 4
max_seq: 9
use_exogenous: False

epochs: 200
batch_size: 32

model_name: 'dgla'
d_hidden: 64
d_emb: 8
d_ff: 64
ff_dropout: 0
kernel_size: 2
decoder_order: 1
n_layers: 1
layer_norm: false
merge: 'mlp'


