dataset_name: 'P12'
window: 215
stride: 215

adj_threshold: 0.1

detrend: False
scale: True
scaling_axis: 'global'  # ['channels', 'global']
scaled_target: True

epochs: 200
batch_size: 64
aggregate_by: ['mean']

model_name: 'dglac'
d_hidden: 32
d_emb: 0
d_ff: 32
ff_dropout: 0
kernel_size: 1
decoder_order: 1
n_layers: 1
n_class: 2
shuffle: True

#lr: 0.001
grad-clip-val: 0.5
grad-clip-algorithm: 'value'