dataset_name: 'P19'
window: 60
stride: 60

adj_threshold: 0.1

detrend: False
scale: True
scaling_axis: 'global'  # ['channels', 'global']
scaled_target: True

epochs: 200
batch_size: 64
aggregate_by: ['mean']

model_name: 'dglac'
d_hidden: 64
d_emb: 0
d_ff: 64
ff_dropout: 0
kernel_size: 1
decoder_order: 1
n_layers: 1
n_class: 2
shuffle: True
